In [1]:
import pandas as pd

df = pd.read_csv('./datasets/TON-IoT/edgelist_ton_iot.csv')
df

,ID,src_ip,dst_ip,label,type,pred,is_train
0,0,172.27.226.140:1883,192.168.1.152:52976,0,0,0,1
1,1,172.24.99.246:47260,192.168.1.255:15600,0,0,0,1
2,2,172.18.57.119:1880,192.168.1.152:51782,0,0,0,0
3,3,172.18.164.17:34296,192.168.1.152:10502,0,0,0,0
4,4,172.29.91.92:46608,192.168.1.190:53,0,0,0,0
...,...,...,...,...,...,...,...
461038,461038,172.20.31.166:33108,176.28.50.165:80,1,8,8,0
461039,461039,172.20.166.189:37242,34.230.157.88:443,1,6,6,1
461040,461040,172.29.243.207:4444,192.168.1.193:49178,1,1,9,1
461041,461041,172.30.171.98:60816,104.98.29.100:443,1,9,7,1
461042,461042,172.24.250.26:41054,151.101.24.64:443,1,9,9,1

In [9]:
filtered_df = df[(df['type'] == 0) & (df['pred'] == 0)][:5]
filtered_df

   ID               src_ip               dst_ip  label  type  pred  is_train
0   0  172.27.226.140:1883  192.168.1.152:52976      0     0     0         1
1   1  172.24.99.246:47260  192.168.1.255:15600      0     0     0         1
2   2   172.18.57.119:1880  192.168.1.152:51782      0     0     0         0
3   3  172.18.164.17:34296  192.168.1.152:10502      0     0     0         0
4   4   172.29.91.92:46608     192.168.1.190:53      0     0     0         0

In [12]:
import numpy as np
np.unique(np.concatenate([filtered_df['src_ip'].values, filtered_df['dst_ip'].values]))

array(['172.18.164.17:34296', '172.18.57.119:1880', '172.24.99.246:47260',
       '172.27.226.140:1883', '172.29.91.92:46608', '192.168.1.152:10502',
       '192.168.1.152:51782', '192.168.1.152:52976', '192.168.1.190:53',
       '192.168.1.255:15600'], dtype=object)

In [18]:
~(np.array([True, False, False]) | np.array([True, True, False]))

array([False, False,  True])

In [21]:
sorted(np.array([3,2,1]))

AttributeError: 'list' object has no attribute 'tolist'